#+OPTIONS: toc:nil
#+TITLE: Build OpenWrt Image for Lichee Pi Nano
#+DATE: 2018-09-17
#+AUTHOR: qinfengling
#+PROPERTY: LANGUAGE en

OpenWrt is an open source linux distribution for embedded devices,

It has support a lot of hardwares, I got a new device called LiChee Pi Nano these days.

So I just add a few patches and template in OpenWrt v18.06.1, it runs perfect well.

This is the way to compile the image from the source code.

** Clone the source code
#+BEGIN_SRC bash
cd ~
git clone -b licheepi-nano https://github.com/qinfengling/openwrt.git
#+END_SRC

** Update the configuration for Lichee Pi Nano
#+BEGIN_SRC bash
cd ~/openwrt
cat > .config << EOL
CONFIG_TARGET_sunxi=y
CONFIG_TARGET_sunxi_arm9=y
CONFIG_TARGET_sunxi_arm9_DEVICE_suniv-f1c100s-licheepi-nano=y
CONFIG_DEVEL=y
CONFIG_BRCMFMAC_SDIO=y
CONFIG_BRCMFMAC_USB=y
CONFIG_DRIVER_11AC_SUPPORT=y
CONFIG_DRIVER_11N_SUPPORT=y
CONFIG_PACKAGE_MAC80211_DEBUGFS=y
CONFIG_PACKAGE_MAC80211_MESH=y
CONFIG_PACKAGE_brcmfmac-firmware-usb=y
CONFIG_PACKAGE_hostapd-common=y
CONFIG_PACKAGE_iw=y
CONFIG_PACKAGE_iwinfo=y
CONFIG_PACKAGE_kmod-ata-ahci-platform=y
CONFIG_PACKAGE_kmod-ata-core=y
CONFIG_PACKAGE_kmod-ata-sunxi=y
CONFIG_PACKAGE_kmod-brcmfmac=y
CONFIG_PACKAGE_kmod-brcmutil=y
CONFIG_PACKAGE_kmod-cfg80211=y
CONFIG_PACKAGE_kmod-libphy=y
CONFIG_PACKAGE_kmod-mac80211=y
CONFIG_PACKAGE_kmod-mmc=y
CONFIG_PACKAGE_kmod-nls-base=y
CONFIG_PACKAGE_kmod-of-mdio=y
CONFIG_PACKAGE_kmod-rtc-sunxi=y
CONFIG_PACKAGE_kmod-rtl8192c-common=y
CONFIG_PACKAGE_kmod-rtl8192cu=y
CONFIG_PACKAGE_kmod-rtl8xxxu=y
CONFIG_PACKAGE_kmod-rtlwifi=y
CONFIG_PACKAGE_kmod-rtlwifi-usb=y
CONFIG_PACKAGE_kmod-scsi-core=y
CONFIG_PACKAGE_kmod-sun4i-emac=y
CONFIG_PACKAGE_kmod-usb-core=y
CONFIG_PACKAGE_libiwinfo=y
CONFIG_PACKAGE_rtl8188eu-firmware=y
CONFIG_PACKAGE_rtl8192cu-firmware=y
CONFIG_PACKAGE_swconfig=y
CONFIG_PACKAGE_wireless-regdb=y
CONFIG_PACKAGE_wpad-mini=y
CONFIG_SOFT_FLOAT=y
CONFIG_TARGET_OPTIONS=y
EOL
#+END_SRC

** Generate the image
#+BEGIN_SRC bash
make world
#+END_SRC

*TIP*: You can also speed up the compile with /-j/ option.

When you finish the compile without any failure, you can find the
image (/openwrt-sunxi-arm9-suniv-f1c100s-licheepi-nano-ext4-sdcard.img.gz/) under *./bin/targets/sunxi/arm9/*,

*NOTE*: ~It is an image for TF card, you need to decompress it first, then write it to the TF card.~

** TODO:
1. Merge to the master branch
2. Add / Del some functions (TBD)

** Reference
https://wiki.openwrt.org/doc/howto/buildroot.exigence#prerequisites

https://medium.com/openwrt-iot/lede-openwrt-installing-firmware-on-a-raspberry-pi-f20af38071d5


